"use client";

import { useState, useCallback, useMemo } from "react";
import ThemeToggle from "../theme-toggle";

interface TarotCard {
  name: string;
  number?: string;
  suit: string;
  arcana: string;
  symbol: string;
  element: string;
  upright: string;
  reversed: string;
  reading: string;
  keywords: string[];
  advice: string;
}

const MAJOR_SYMBOLS: Record<string, string> = {
  "The Fool": "0", "The Magician": "I", "The High Priestess": "II", "The Empress": "III",
  "The Emperor": "IV", "The Hierophant": "V", "The Lovers": "VI", "The Chariot": "VII",
  "Strength": "VIII", "The Hermit": "IX", "Wheel of Fortune": "X", "Justice": "XI",
  "The Hanged Man": "XII", "Death": "XIII", "Temperance": "XIV", "The Devil": "XV",
  "The Tower": "XVI", "The Star": "XVII", "The Moon": "XVIII", "The Sun": "XIX",
  "Judgement": "XX", "The World": "XXI",
};

const MAJOR_ARCANA: TarotCard[] = [
  { name: "The Fool", number: "0", suit: "Major Arcana", arcana: "major", symbol: "∞", element: "Air", upright: "New beginnings, innocence, spontaneity, free spirit", reversed: "Recklessness, risk-taking, holding back, foolishness", reading: "The Fool stands at the edge of a cliff, a small bag on a stick over his shoulder, a white rose in his hand. He is about to step into the unknown, and he is not afraid. This card represents the pure, uncorrupted spirit of adventure that exists in every beginning. The Fool is not ignorant — he is trusting. He trusts that the universe will support his journey, that the cliff is not a dead end but a launching point. In readings, The Fool asks you to look at where in your life you have been playing it too safe. Where have you been letting fear of the unknown keep you standing still? The path ahead does not require a map. It requires only the courage to take the first step. The white rose in The Fool's hand symbolizes purity of intention. Your motives do not need to be fully formed. They only need to be genuine. Take the leap. The net will appear.", keywords: ["beginnings", "innocence", "adventure"], advice: "Take the leap of faith. The universe catches those who trust the journey." },
  { name: "The Magician", number: "I", suit: "Major Arcana", arcana: "major", symbol: "∞", element: "Air", upright: "Willpower, desire, resourcefulness, skill", reversed: "Trickery, manipulation, untapped talents, waste", reading: "The Magician stands before a table bearing the four symbols of the tarot suits — a cup, a pentacle, a sword, and a wand. One hand points to the sky, the other to the earth. He is the bridge between heaven and earth, the conduit through which divine energy becomes material reality. You have everything you need. Not tomorrow, not after you acquire something else — right now. The Magician is the alchemist of the tarot, the force that transforms intention into action, vision into reality. Your skills, talents, and resources are all present and available. The question is not whether you are ready — you are. The question is whether you will act. The Magician warns against the misuse of power. In its reversed position, it suggests that you may be using your talents for manipulation rather than creation, or that your gifts are lying dormant while you wait for permission that no one is going to give you.", keywords: ["power", "creation", "skill"], advice: "You have all the tools you need. Now use them with intention." },
  { name: "The High Priestess", number: "II", suit: "Major Arcana", arcana: "major", symbol: "☽", element: "Water", upright: "Intuition, sacred knowledge, divine feminine, mystery", reversed: "Secrets, withdrawal, silence, repressed intuition", reading: "The High Priestess sits between two pillars — one black, one white — holding a scroll of sacred knowledge partially hidden by her robes. Behind her, a veil embroidered with pomegranates conceals the waters of the unconscious. She is the guardian of the threshold between the conscious and subconscious mind, the known and the unknown. She represents the deep, intuitive knowing that cannot be explained by logic or proven by evidence. You already know the answer. The problem is not that you lack information — it is that you are not trusting what you already feel. The High Priestess asks you to stop searching outside yourself for guidance and to turn inward. Her message comes most clearly in dreams, in quiet moments, in the subtle nudges you have been ignoring. The veil before you is thin. Behind it lies everything you have been seeking.", keywords: ["intuition", "mystery", "inner knowledge"], advice: "The answers you seek are within. Silence the noise and listen." },
  { name: "The Empress", number: "III", suit: "Major Arcana", arcana: "major", symbol: "♀", element: "Earth", upright: "Femininity, beauty, nature, nurturing, abundance", reversed: "Creative block, dependence, emptiness, neglect", reading: "The Empress sits on a throne of cushions in a lush field of wheat, a crown of twelve stars on her head and a scepter in her hand. She is the mother of the tarot, the embodiment of fertility, abundance, and the nurturing force of nature itself. She represents the creative power that flows through all living things — the force that makes the wheat grow, that fills the river with water, that brings new life into the world. This card appears when it is time to nurture something. A project, a relationship, a creative work, or yourself. The Empress reminds you that creation is not only about making — it is about allowing, receiving, and tending. The abundance of the universe is not something you need to force. It is something you need to open yourself to. In its reversed position, The Empress suggests a block in this flow of creative or nurturing energy, often caused by neglecting your own needs while caring for others.", keywords: ["abundance", "nurturing", "nature"], advice: "Allow yourself to be nourished. From fullness, you can give to others." },
  { name: "The Emperor", number: "IV", suit: "Major Arcana", arcana: "major", symbol: "♂", element: "Fire", upright: "Authority, structure, stability, protection, fatherhood", reversed: "Tyranny, rigidity, lack of discipline, domination", reading: "The Emperor sits on a stone throne adorned with ram's heads, holding an ankh in one hand and a globe in the other. Behind him, barren mountains rise against a red sky. He is the father figure of the tarot, representing structure, authority, and the establishment of order. The Emperor appears when you need to bring discipline to your life. Creativity and intuition have their place, but without structure, they remain unrealized potential. The Emperor asks you to build the framework that will support your vision — to set boundaries, establish routines, and take responsibility for your own authority. He reminds you that true leadership is not about controlling others but about creating the conditions in which things can grow. In its reversed position, this card warns against rigidity, abuse of power, or a refusal to take responsibility.", keywords: ["authority", "structure", "stability"], advice: "Build your foundation with discipline. True power serves order, not chaos." },
  { name: "The Hierophant", number: "V", suit: "Major Arcana", arcana: "major", symbol: "♁", element: "Earth", upright: "Wisdom, tradition, spiritual guidance, conformity", reversed: "Rebellion, unconventionality, personal beliefs, restriction", reading: "The Hierophant sits between two pillars, wearing a triple crown and holding a staff topped with three rings. At his feet, two acolytes kneel, awaiting his teaching. He is the keeper of sacred knowledge, the bridge between the individual and the collective wisdom of tradition. He represents the value of established institutions, formal education, and spiritual guidance passed down through generations. This card appears when you are being called to seek guidance from a teacher, mentor, or established tradition. Not everything needs to be figured out alone. The wisdom of those who came before you is available for the asking. The Hierophant also represents commitment to shared values and participation in community rituals. In its reversed position, this card suggests a need to break free from dogmatic thinking or to question authority that has become rigid.", keywords: ["tradition", "wisdom", "guidance"], advice: "Seek the teacher, but question the dogma. Wisdom lives between tradition and revelation." },
  { name: "The Lovers", number: "VI", suit: "Major Arcana", arcana: "major", symbol: "∞", element: "Air", upright: "Love, harmony, relationships, values alignment, choices", reversed: "Imbalance, misalignment, broken trust, values conflict", reading: "The Lovers card shows a man and woman beneath a winged angel who blesses their union. Behind the woman, the Tree of Knowledge; behind the man, the Tree of Life. This is one of the most misunderstood cards in the tarot. It is not primarily about romantic love — though it can represent that. At its deepest level, The Lovers is about choice. The choice to align your actions with your values. The choice to commit to a path that honors your whole self. The moment of decision is here. You stand at a crossroads where the options may look very different on the surface, but the real choice is the same: will you choose from love or from fear? Will you choose what is true to your heart or what seems safe and expected? The angel above blesses the union not of two people, but of the divided parts of yourself. When you choose from integrity, the universe supports your decision.", keywords: ["love", "harmony", "choice"], advice: "Choose from love, not fear. The right path aligns your heart and your values." },
  { name: "The Chariot", number: "VII", suit: "Major Arcana", arcana: "major", symbol: "∞", element: "Water", upright: "Willpower, determination, victory, control, confidence", reversed: "Lack of direction, aggression, obstacles, defeat", reading: "The Chariot depicts a warrior standing in a chariot pulled by two sphinxes — one black, one white — moving in opposite directions. The warrior holds no reins, controlling the sphinxes through will alone. This card represents the triumph of willpower over opposing forces. The two sphinxes represent the dualities of life — light and dark, conscious and unconscious, action and patience. The Chariot appears when you are being called to harness these opposing forces within yourself and direct them toward a single goal. Victory is not achieved by eliminating one side or the other, but by integrating both and channeling their combined power. The warrior in the chariot does not fight the sphinxes — he guides them. You have more strength than you realize. The obstacles before you are not insurmountable. They are the resistance that will make your victory meaningful.", keywords: ["willpower", "victory", "determination"], advice: "Harness your opposing forces and drive them forward as one." },
  { name: "Strength", number: "VIII", suit: "Major Arcana", arcana: "major", symbol: "♀", element: "Fire", upright: "Courage, inner strength, compassion, influence", reversed: "Self-doubt, weakness, insecurity, low confidence", reading: "Strength shows a woman gently closing the jaws of a lion with her bare hands. Above her head, the infinity symbol hovers. Unlike The Chariot, which represents external willpower, Strength represents inner fortitude — the quiet courage that comes from the heart rather than the ego. The woman in this card does not wrestle the lion; she tames it with patience, love, and understanding. The lion represents your primal instincts, your fears, your raw emotions. Strength does not try to destroy the lion — she recognizes that the lion's power, when directed wisely, is her greatest ally. This card appears when you are being asked to face a challenge with gentleness rather than aggression. Your greatest strength right now lies not in force but in patience. Not in domination but in compassion. The softest touch can calm the wildest beast. Trust your inner resilience.", keywords: ["courage", "inner strength", "compassion"], advice: "True strength is gentle. You do not need to roar to be powerful." },
  { name: "The Hermit", number: "IX", suit: "Major Arcana", arcana: "major", symbol: "∞", element: "Earth", upright: "Soul-searching, introspection, solitude, inner guidance", reversed: "Isolation, loneliness, withdrawal, lost purpose", reading: "The Hermit stands alone on a snowy mountain peak, holding a lantern containing a single star. His staff supports him as he climbs higher into the solitude of the heights. He has withdrawn from the world, but not out of fear. He has withdrawn to find the light that can only be found in stillness. This card appears when you need to step back from the noise of daily life and spend time in introspection. The answers you are seeking cannot be found in the opinions of others or in the distractions of the external world. They can only be found in the quiet of your own heart. The Hermit's lantern contains the light of your own inner wisdom. It has always been there, but it has been obscured by the brightness of the world. This is a time for solitude, for contemplation, for the kind of deep soul-searching that can only happen in silence. Trust the path that reveals itself in stillness.", keywords: ["introspection", "solitude", "wisdom"], advice: "Retreat is not defeat. The light you find in solitude will guide others too." },
  { name: "Wheel of Fortune", number: "X", suit: "Major Arcana", arcana: "major", symbol: "♃", element: "Fire", upright: "Change, cycles, destiny, turning point, fortune", reversed: "Bad luck, resistance to change, disruption, setbacks", reading: "The Wheel of Fortune is the great cycle of life, death, and rebirth depicted as a wheel inscribed with magical symbols, turning endlessly. At its corners sit four winged creatures representing the fixed signs of the zodiac. A serpent descends on one side, a jackal-headed figure rises on the other, and a sphinx sits at the top, holding a sword. The wheel turns constantly, and no one stays at the top or bottom forever. This card marks a turning point. The cycle is shifting, and events beyond your control are moving into motion. The Wheel of Fortune reminds you that change is the only constant. What is at the top today may be at the bottom tomorrow, and vice versa. Your task is not to cling to any particular position on the wheel but to find your center, where the turning does not disturb you. This is a time of destiny — not in the sense that your choices do not matter, but in the sense that forces larger than yourself are at work. Flow with them.", keywords: ["change", "cycles", "destiny"], advice: "The wheel turns for everyone. This too shall pass — the good and the bad." },
  { name: "Justice", number: "XI", suit: "Major Arcana", arcana: "major", symbol: "♎", element: "Air", upright: "Fairness, truth, law, accountability, cause and effect", reversed: "Injustice, dishonesty, unaccountability, imbalance", reading: "Justice sits on a throne, holding a sword in one hand and scales in the other. She is neither merciful nor cruel — she is simply accurate. Her eyes are open, her gaze direct. She sees clearly and judges fairly. Justice represents the law of cause and effect — the principle that every action has a consequence, that truth eventually surfaces, and that balance will be restored. This card appears when a decision must be made, a truth must be faced, or a situation must be evaluated with complete honesty. Justice does not care about your excuses or your justifications. She cares only about what is true. If you have been acting with integrity, this card confirms that fairness will prevail. If you have been dishonest, it warns that the scales will tip against you. The sword of Justice cuts through illusion, and the scales measure what is hidden. Truth will out. Let it.", keywords: ["justice", "truth", "fairness"], advice: "What you put into the world returns to you. Act with integrity." },
  { name: "The Hanged Man", number: "XII", suit: "Major Arcana", arcana: "major", symbol: "∞", element: "Water", upright: "Surrender, new perspective, suspension, pause", reversed: "Delay, resistance, stalling, martyrdom", reading: "The Hanged Man hangs upside down from a T-shaped cross, one leg crossed behind the other, his hands tied behind his back. His expression is peaceful, almost serene. A halo glows around his head. He has not been hanged as punishment — he has chosen this suspension willingly, to see the world from a different angle. This card appears when you are being asked to surrender. Not to give up, but to release your grip on a situation that you cannot control by force. The Hanged Man represents the wisdom of waiting, of seeing things from a different perspective, of allowing a solution to emerge rather than forcing it. Your current approach is not working because you are trying too hard. Stop struggling. The answer you seek will not be found by doing more — it will be found by seeing differently. Hang upside down for a while. The world looks different from here, and that is exactly what you need.", keywords: ["surrender", "perspective", "pause"], advice: "Stop struggling. The answer comes when you stop forcing and start seeing." },
  { name: "Death", number: "XIII", suit: "Major Arcana", arcana: "major", symbol: "♏", element: "Water", upright: "Transformation, endings, change, transition, release", reversed: "Resistance to change, stagnation, decay, fear of endings", reading: "Death rides a white horse, carrying a black banner emblazoned with a white rose. Before him, a king lies fallen, a bishop prays, a child looks on with curiosity. The sun rises between two towers in the background. This is perhaps the most feared card in the deck, but its meaning is profoundly misunderstood. Death does not represent physical death. It represents transformation — the ending of one phase so that another can begin. Something in your life is ending. A relationship, a career, a belief system, a way of being. This ending is not a punishment; it is a necessary part of your growth. The Death card asks you to release what no longer serves you with grace rather than resistance. The natural world teaches us that death is always followed by new life. The leaf falls, the tree rests, and in spring, new buds appear. Trust the cycle. What you are releasing is making space for what is to come.", keywords: ["transformation", "endings", "rebirth"], advice: "Something must end so something greater can begin. Do not fear the death of what no longer serves you." },
  { name: "Temperance", number: "XIV", suit: "Major Arcana", arcana: "major", symbol: "♐", element: "Fire", upright: "Balance, moderation, patience, harmony, purpose", reversed: "Imbalance, excess, discord, lack of patience", reading: "Temperance depicts an angel pouring liquid between two cups — one in each hand. One foot is in the water, the other on the earth. A path leads toward a distant mountain range, and the sun rises behind it. The angel is the alchemist of the soul, blending opposing forces into a harmonious whole. Temperance is the card of the golden mean — the middle path between extremes. It appears when you are being called to find balance in your life. Not the balance of equal parts, but the dynamic balance of a living system that constantly adjusts to changing conditions. You have been running hot or cold, too much or too little, all in or all out. Temperance asks you to find the rhythm that sustains you. Patience is the key. The alchemical process cannot be rushed. Lead is not turned into gold in a single moment. It is a gradual transformation that requires steady, consistent attention. Blend, adjust, and trust the process.", keywords: ["balance", "moderation", "harmony"], advice: "Find the middle path. Extremes exhaust you; balance sustains you." },
  { name: "The Devil", number: "XV", suit: "Major Arcana", arcana: "major", symbol: "♑", element: "Earth", upright: "Bondage, materialism, shadow self, addiction, obsession", reversed: "Release, freedom, reclaiming power, detachment", reading: "The Devil sits on a pedestal, with a man and a woman chained at his feet. He has bat wings, a goat's head, and a pentagram on his forehead. The chains around the figures are loose — they could easily slip free, but they do not. The Devil represents bondage of your own making. The chains are not locked. You can walk away anytime. But there is something you are attached to — a habit, a relationship, a belief, a material possession — that you believe you cannot live without. This card confronts you with the shadow aspects of yourself that you have been avoiding. Your addictions, your obsessions, your patterns of self-destruction. The Devil does not force you to stay. He simply offers an illusion so compelling that you choose to remain. The bright side of this card is that recognizing your chains is the first step to freedom. The Devil reversed signals a moment of liberation — the choice to walk away from what has been holding you captive. You have the power to free yourself.", keywords: ["shadow", "bondage", "materialism"], advice: "Recognize the chains you have accepted as yours. You can walk out of this prison anytime." },
  { name: "The Tower", number: "XVI", suit: "Major Arcana", arcana: "major", symbol: "♄", element: "Fire", upright: "Sudden change, upheaval, revelation, awakening", reversed: "Avoidance of disaster, fear of change, delayed destruction", reading: "The Tower shows a stone structure struck by lightning, its crown blasted off. Two figures fall headfirst from the windows. Flames consume the upper levels. Dark clouds gather. And yet, the sky behind the clouds is blue. The Tower is the card of sudden, dramatic change — the kind of change that comes without warning and shatters the structures you thought were permanent. This card represents a moment of truth. The foundation was already cracked; the lightning only revealed what was already true. Your house of cards is falling, and it hurts. But here is what The Tower teaches: what is built on falsehood must eventually fall. The structure that is crumbling was never as solid as you believed. The Tower clears the ground for something authentic to be built. It is brutal, but it is honest. In its wake comes clarity. The flash of lightning illuminates what was hidden in the shadows. The truth, however painful, is ultimately freeing. Let it fall. Let it all fall. What remains after the rubble is cleared is the only thing you ever really needed.", keywords: ["upheaval", "revelation", "awakening"], advice: "When the tower falls, the foundations were already cracked. Build again on truth." },
  { name: "The Star", number: "XVII", suit: "Major Arcana", arcana: "major", symbol: "♒", element: "Air", upright: "Hope, inspiration, serenity, renewal, purpose", reversed: "Hopelessness, discouragement, lack of faith, despair", reading: "The Star shows a naked woman kneeling beside a pool of water, pouring water from two pitchers — one into the pool, one onto the land. Behind her, a single large star shines, surrounded by seven smaller stars. A bird perches in a tree in the distance. After The Tower's destruction comes The Star's healing. This is the card of hope, renewal, and spiritual connection. It appears after a period of upheaval to remind you that the universe is still abundant, still beautiful, still worthy of your trust. The Star represents a moment of peace and clarity. The chaos has passed, and you can finally breathe. The water flowing from the pitchers symbolizes the flow of life, of inspiration, of grace. You are being replenished after a difficult time. The Star asks you to open your heart to hope. Not naive optimism that ignores reality, but the deep, spiritual knowing that you are part of something larger than yourself, and that larger something is good. You are being guided. Trust the light that leads you forward.", keywords: ["hope", "inspiration", "renewal"], advice: "After destruction comes the star. Let hope guide you through the darkness." },
  { name: "The Moon", number: "XVIII", suit: "Major Arcana", arcana: "major", symbol: "♋", element: "Water", upright: "Illusion, fear, anxiety, subconscious, intuition", reversed: "Fear released, repressed emotion, clarity awakening", reading: "The Moon depicts a night scene with a full moon shining between two towers. A path leads through the wilderness into the distance, passing a wolf and a dog who howl at the moon. A crayfish emerges from the water onto the land. The Moon represents the realm of the subconscious, of dreams, of fears, and of illusion. This card appears when things are not as they seem. The path is unclear, the shadows are deep, and your mind is filling in the gaps with fear. The Moon asks you to navigate uncertainty with your intuition rather than your logic. You cannot see clearly right now, and that is by design. Some truths can only be approached indirectly, revealed gradually as your eyes adjust to the darkness. The wolf and the dog represent the wild and the tame aspects of your own nature. The crayfish emerging from the water represents thoughts rising from the depths of your subconscious. Pay attention to your dreams, your fears, your unexpected emotions. They are trying to tell you something important.", keywords: ["illusion", "fear", "subconscious"], advice: "Not everything is as it seems. Trust your intuition to navigate the shadows." },
  { name: "The Sun", number: "XIX", suit: "Major Arcana", arcana: "major", symbol: "☉", element: "Fire", upright: "Joy, success, celebration, vitality, positivity", reversed: "Temporary sadness, burnout, dimmed enthusiasm, blocked joy", reading: "The Sun shows a bright, radiant sun shining over a walled garden. Inside, a naked child rides a white horse, arms outstretched in pure joy. Sunflowers bloom behind the wall, turning their faces toward the light. The Sun is the most positive card in the tarot. It represents joy, success, vitality, and the free expression of your true self. After the shadowy uncertainties of The Moon, The Sun brings clarity, warmth, and celebration. This card appears when you are emerging into the light. A period of difficulty is ending, and you can finally enjoy the fruits of your labor. The child on the horse represents your inner self — innocent, joyful, unburdened by the weight of the world. The Sun asks you to reconnect with that child. To play. To celebrate. To allow yourself to be happy without guilt. The sun shines on everyone, but not everyone is willing to step into its light. You have earned this moment. Accept it fully and let your true self shine.", keywords: ["joy", "success", "vitality"], advice: "You have made it through the darkness. Now bask in the light you deserve." },
  { name: "Judgement", number: "XX", suit: "Major Arcana", arcana: "major", symbol: "♃", element: "Fire", upright: "Reflection, reckoning, inner calling, absolution", reversed: "Self-doubt, refusal of self-evaluation, harsh judgment", reading: "Judgement depicts angels blowing trumpets as the dead rise from their tombs. Below, a family emerges from a stone casket, arms raised in awe and gratitude. The waters around them are choppy, and mountains rise in the distance. Judgement is the card of awakening, of hearing a call that compels you to rise and meet your destiny. This is not the judgment of an external authority. It is the judgment of your own soul, the moment of reckoning with who you have been and who you are meant to become. The trumpets are sounding an invitation. You are being called to a higher purpose, to a life that is more aligned with your deepest values. The dead rising from their tombs represent the parts of yourself that have been buried — your potential, your forgotten dreams, your unexpressed gifts. It is time for them to live again. Judgement asks you to answer the call. If you have been avoiding a necessary evaluation of your life, this card demands that you face it with honesty and courage. The reckoning is here. Rise to meet it.", keywords: ["judgment", "rebirth", "calling"], advice: "The call is coming from inside. Answer it honestly, without judgment of yourself." },
  { name: "The World", number: "XXI", suit: "Major Arcana", arcana: "major", symbol: "♁", element: "Earth", upright: "Completion, fulfillment, accomplishment, wholeness", reversed: "Incompletion, delays, stagnation, lack of closure", reading: "The World shows a woman dancing within a wreath of leaves, holding a wand in each hand. At the four corners of the card are the same four figures from the Wheel of Fortune — the angel, the eagle, the ox, and the lion — representing the four fixed signs of the zodiac and the four elements. The World is the final card of the Major Arcana, representing completion, fulfillment, and the successful conclusion of a major life cycle. You have made it. The journey that began with The Fool — stepping off the cliff into the unknown — has reached its culmination. You have learned the lessons, faced the challenges, and integrated the wisdom of every card you have encountered along the way. The World represents a moment of profound accomplishment and wholeness. A cycle is complete, and you are ready for the next one. The dancer in the center of the wreath is moving with joy and freedom because she has achieved mastery — not mastery over the world, but mastery of herself. Celebrate your achievement, but do not linger too long in completion. The Fool is already standing at the edge of a new cliff, waiting for you to take the next step.", keywords: ["completion", "fulfillment", "wholeness"], advice: "One cycle ends, another begins. Celebrate how far you have come." },
];

const SUITS: Record<string, { element: string; symbol: string; meaning: string }> = {
  Wands: { element: "Fire", symbol: "♠", meaning: "Creativity, action, ambition, inspiration" },
  Cups: { element: "Water", symbol: "♥", meaning: "Emotions, relationships, intuition, love" },
  Swords: { element: "Air", symbol: "♣", meaning: "Thought, conflict, truth, intellect" },
  Pentacles: { element: "Earth", symbol: "♦", meaning: "Material world, work, health, prosperity" },
};

const MINOR_NUMBERS = ["Ace", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Page", "Knight", "Queen", "King"];

const SUIT_COLORS: Record<string, string> = {
  Wands: "#e67e22", Cups: "#2980b9", Swords: "#c0392b", Pentacles: "#27ae60",
};

const MINOR_READINGS: Record<string, Record<string, TarotCard>> = {
  Wands: {
    Ace: { name: "Ace of Wands", number: "Ace", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "New beginning, inspiration, creative spark, potential", reversed: "Delays, lack of motivation, blocked creativity", reading: "The Ace of Wands is a spark of inspiration, a burst of creative energy that ignites your passion. This card represents a new beginning that comes from within — a desire, a vision, or a project that sets your soul on fire. The wand in this card is alive with leaves and shoots, symbolizing growth and potential. An opportunity is presenting itself, one that aligns with your true passion. This is not a time for overthinking. The energy of the Ace is raw, fresh, and urgent. Strike while the iron is hot.", keywords: ["inspiration", "new beginning", "potential"], advice: "A spark of inspiration has arrived. Strike while the fire is hot." },
    Two: { name: "Two of Wands", number: "Two", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Planning, decisions, future vision, discovery", reversed: "Indecision, fear of unknown, lack of planning", reading: "The Two of Wands shows a figure standing between two wands, holding a globe and looking out at the horizon. You have reached a point where your initial inspiration must now be planned and directed. The horizon represents the possibilities before you, but you must choose which direction to take. This card is about making decisions that will shape your future. You have outgrown your current situation. The world is calling you to explore, to expand, and to commit to a path.", keywords: ["planning", "decisions", "vision"], advice: "The world is in your hands. Choose your direction with both courage and foresight." },
    Three: { name: "Three of Wands", number: "Three", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Expansion, progress, growth, teamwork, foresight", reversed: "Obstacles, delays, frustration, lack of teamwork", reading: "The Three of Wands depicts a figure on a cliff, watching ships sail into the distance. Your plans are in motion. The seeds you planted are beginning to grow, and progress is visible. This card represents expansion — your influence, your reach, and your vision are extending beyond their previous boundaries. The ships returning with goods suggest that your investments of time and energy are beginning to pay off. Keep your eyes on the horizon, but remain involved in the details of the journey.", keywords: ["expansion", "progress", "teamwork"], advice: "Your vision is taking shape. Trust the process and those who journey with you." },
    Four: { name: "Four of Wands", number: "Four", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Celebration, stability, community, homecoming", reversed: "Lack of belonging, restlessness, cancelled plans", reading: "The Four of Wands shows a celebration under a canopy of four wands. This card represents a moment of joy, stability, and community. You have achieved a milestone, and it is time to celebrate with those you love. The foundations are solid, the home is warm, and the heart is full. This is a card of gratitude and togetherness. Take a moment to appreciate how far you have come and the people who have supported you along the way.", keywords: ["celebration", "stability", "community"], advice: "Celebrate what you have built. Joy shared is joy multiplied." },
    Five: { name: "Five of Wands", number: "Five", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Competition, conflict, tension, rivalry", reversed: "Avoidance of conflict, reconciliation, peace restored", reading: "The Five of Wands shows five figures wielding wands in a chaotic struggle. This card represents conflict, competition, and the friction that arises when different wills collide. Not all conflict is negative — healthy competition can sharpen your skills and clarify your desires. This card asks you to examine the role of conflict in your life. Are you fighting for something meaningful, or are you caught in a battle of egos? Choose your battles wisely.", keywords: ["competition", "conflict", "tension"], advice: "Not every battle is worth fighting. Choose your battles with wisdom." },
    Six: { name: "Six of Wands", number: "Six", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Victory, recognition, public acclaim, progress", reversed: "Ego, arrogance, fall from grace, lack of recognition", reading: "The Six of Wands shows a figure riding a horse, crowned with laurels, as a crowd cheers. This is the card of victory and public recognition. You have achieved something significant, and others are acknowledging your success. Accept the praise graciously, but remain humble. The laurel wreath of victory is a symbol of your accomplishment, but the moment of glory is temporary. Enjoy it fully while it lasts.", keywords: ["victory", "recognition", "acclaim"], advice: "Your success is well earned. Accept the recognition with humility." },
    Seven: { name: "Seven of Wands", number: "Seven", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Challenge, competition, perseverance, resilience", reversed: "Giving up, overwhelmed, lack of focus", reading: "The Seven of Wands shows a figure on higher ground, defending against six wands attacking from below. You are being challenged, and you must hold your ground. This card represents standing up for your position in the face of opposition. You have the advantage of the higher ground — your position is stronger than you realize. Do not back down. Your perseverance will see you through the challenge.", keywords: ["challenge", "perseverance", "resilience"], advice: "Stand your ground. The challenge before you is testing your commitment." },
    Eight: { name: "Eight of Wands", number: "Eight", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Speed, action, progress, movement, swift change", reversed: "Delays, rush, impatience, scattered energy", reading: "The Eight of Wands depicts eight wands flying through the air at great speed. This card represents rapid progress, swift action, and forward momentum. Things that have been stalled are now moving quickly. Events are accelerating, and you may feel like you are in a whirlwind of activity. Trust the momentum and stay focused on your goals, but avoid rushing into decisions without proper consideration.", keywords: ["speed", "action", "progress"], advice: "The winds of change are at your back. Move swiftly but not recklessly." },
    Nine: { name: "Nine of Wands", number: "Nine", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Resilience, courage, persistence, boundaries", reversed: "Burnout, exhaustion, defensiveness, giving up", reading: "The Nine of Wands shows a wounded figure standing guard behind eight wands, holding the ninth. This card represents resilience in the face of adversity. You have been through a battle, and you are tired — but you are still standing. The last stand requires the most courage. This card encourages you to maintain your boundaries and persist a little longer. The end is near, and your efforts will be rewarded.", keywords: ["resilience", "courage", "persistence"], advice: "You have come so far. Rest if you must, but do not give up." },
    Ten: { name: "Ten of Wands", number: "Ten", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Burden, overcommitment, responsibility, stress", reversed: "Release from burden, sharing load, lightening up", reading: "The Ten of Wands shows a figure carrying a heavy bundle of ten wands, struggling under the weight. This card represents the burden of too much responsibility. You have taken on more than you can carry, and the weight is becoming overwhelming. This card asks you to examine where you can delegate, release, or reprioritize. You do not have to carry everything alone. The load will be lighter if you share it.", keywords: ["burden", "responsibility", "pressure"], advice: "The weight you carry is heavy, but it will not last forever. Delegate and breathe." },
    Page: { name: "Page of Wands", number: "Page", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Enthusiasm, exploration, discovery, free spirit", reversed: "Lack of direction, setbacks, immaturity", reading: "The Page of Wands represents youthful enthusiasm and the spirit of exploration. A message of creative opportunity is arriving. The Page carries a wand with fresh leaves sprouting from it, symbolizing new growth and potential. Approach this opportunity with curiosity and an open mind. You may not have all the answers yet, but your passion will carry you forward.", keywords: ["enthusiasm", "exploration", "discovery"], advice: "Approach life with curiosity. The journey itself is the teacher." },
    Knight: { name: "Knight of Wands", number: "Knight", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Action, adventure, impulsiveness, energy", reversed: "Recklessness, haste, burnout, delays", reading: "The Knight of Wands charges forward on his horse, full of passion and energy. This card represents bold action, adventure, and the courage to pursue what you want. The Knight does not wait for permission — he takes action. Your energy is high, and your confidence is strong. Use this momentum to move forward on your goals, but be mindful not to act impulsively without considering the consequences.", keywords: ["action", "adventure", "energy"], advice: "Charge forward with passion, but know when to slow down and plan." },
    Queen: { name: "Queen of Wands", number: "Queen", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Warmth, determination, confidence, independence", reversed: "Jealousy, self-doubt, insecurity, imbalance", reading: "The Queen of Wands embodies warmth, confidence, and magnetic charisma. She is the personification of creative energy channeled with purpose and determination. She knows what she wants and is not afraid to pursue it. Her warmth draws people to her, and her confidence inspires them. This card asks you to step into your own power with grace and courage. You have the ability to inspire others through your passion and determination.", keywords: ["warmth", "determination", "independence"], advice: "Lead with both fire and grace. Your confidence inspires those around you." },
    King: { name: "King of Wands", number: "King", suit: "Wands", arcana: "minor", symbol: SUITS.Wands.symbol, element: SUITS.Wands.element, upright: "Leadership, vision, entrepreneur, honor", reversed: "Demanding, overbearing, ruthless, inflexible", reading: "The King of Wands represents visionary leadership and entrepreneurial spirit. He has achieved mastery over the realm of fire — his passion is now tempered with wisdom, his ambition guided by integrity. He is a natural leader who inspires others through his vision and example. This card asks you to step into a leadership role with confidence and honor. Your vision is clear, and you have the experience to bring it to life.", keywords: ["leadership", "vision", "entrepreneur"], advice: "Lead with vision and integrity. True leadership is service, not domination." },
  },
  Cups: {
    Ace: { name: "Ace of Cups", number: "Ace", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Love, new relationships, emotional overflow, compassion", reversed: "Blocked emotions, emptiness, loneliness, withheld love", reading: "The Ace of Cups represents the overflowing of love and emotional abundance. A cup overflows with water, symbolizing the infinite depth of love that is available to you. This card often appears at the beginning of a new relationship, a deepening of existing bonds, or a spiritual awakening of the heart. Your emotional cup is full. Share your love freely and without conditions.", keywords: ["love", "new beginnings", "emotion"], advice: "Your heart is opening. Let love flow freely without conditions." },
    Two: { name: "Two of Cups", number: "Two", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Partnership, unity, connection, mutual attraction", reversed: "Separation, imbalance, broken connection, withdrawal", reading: "The Two of Cups depicts a man and a woman exchanging cups, a symbol of their mutual love and respect. A caduceus between them represents healing and balance. This card represents a deep connection between two people, whether romantic, platonic, or professional. It is a card of partnership, unity, and mutual respect. When this card appears, it signals a harmonious relationship built on equal giving and receiving.", keywords: ["partnership", "unity", "connection"], advice: "When two hearts align, the whole becomes greater than the sum of its parts." },
    Three: { name: "Three of Cups", number: "Three", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Celebration, friendship, community, gatherings", reversed: "Isolation, loneliness, canceled plans, overindulgence", reading: "The Three of Cups shows three women raising their cups in celebration. This card represents friendship, community, and shared joy. It is a time to celebrate with those you love, to nurture your social connections, and to express gratitude for the people who enrich your life. Joy multiplies when it is shared. Reach out to your community and celebrate the bonds that sustain you.", keywords: ["celebration", "friendship", "community"], advice: "Rejoice with those you love. Shared joy deepens every bond." },
    Four: { name: "Four of Cups", number: "Four", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Meditation, contemplation, apathy, reevaluation", reversed: "New perspective, readiness, action, awakening", reading: "The Four of Cups shows a figure sitting under a tree, looking at three cups while a fourth is offered by a hand from the sky. This card represents a period of contemplation and reevaluation. You may be feeling apathetic or dissatisfied with what is being offered to you. The hand from the sky offers a new opportunity, but you are so focused on what you already have that you do not see it. Open your eyes to new possibilities.", keywords: ["meditation", "apathy", "reevaluation"], advice: "Sometimes you stare so long at what you want that you miss what you already have." },
    Five: { name: "Five of Cups", number: "Five", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Loss, grief, regret, disappointment, sorrow", reversed: "Acceptance, moving on, release of grief, finding peace", reading: "The Five of Cups shows a figure in a black cloak, staring at three spilled cups while two remain standing behind them. This card represents grief, loss, and disappointment. You are focusing on what has been lost, but there is still something of value remaining. It is okay to grieve what is gone, but do not let your grief blind you to what still remains. The two cups behind you contain the love and support that still exist in your life.", keywords: ["loss", "grief", "sorrow"], advice: "Grief is the price of love. Honor your sorrow, then let it teach you." },
    Six: { name: "Six of Cups", number: "Six", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Nostalgia, memories, childhood, innocence, reunion", reversed: "Stuck in past, unrealistic nostalgia, moving forward", reading: "The Six of Cups depicts two children in a garden, one offering a cup to the other. This card represents nostalgia, innocence, and memories of the past. A reunion with someone from your past may be coming, or you may be feeling called to reconnect with the simpler joys of life. While the past holds treasures, be careful not to romanticize it at the expense of the present.", keywords: ["nostalgia", "memories", "reunion"], advice: "The past holds treasures, but do not live in its reflection. The present is also a gift." },
    Seven: { name: "Seven of Cups", number: "Seven", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Fantasy, choices, illusion, options, wishful thinking", reversed: "Clarity, focus, realistic goals, narrowing choices", reading: "The Seven of Cups shows a figure confronted by seven cups containing various visions and desires. This card represents the power of choice and the danger of illusion. You have many options, but not all of them are what they seem. Some are fantasies, some are distractions, and only a few are truly aligned with your highest good. The challenge is to discern which cup holds genuine fulfillment and which holds only an illusion.", keywords: ["fantasy", "choices", "illusions"], advice: "Not every glittering option is real. Ground your dreams in what is possible." },
    Eight: { name: "Eight of Cups", number: "Eight", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Moving on, leaving behind, withdrawal, seeking truth", reversed: "Fear of moving on, clinging, aimless drifting", reading: "The Eight of Cups shows a figure walking away from a stack of eight cups, heading into the mountains. This card represents the decision to leave behind what no longer serves you in order to seek deeper meaning. The cups are neatly stacked, representing emotional stability — yet you are walking away. This is not an easy decision, but it is a necessary one. Something is calling you toward a deeper truth, and you must follow it, even if it means leaving comfort behind.", keywords: ["moving on", "withdrawal", "seeking truth"], advice: "Sometimes walking away is the bravest thing you can do." },
    Nine: { name: "Nine of Cups", number: "Nine", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Contentment, satisfaction, abundance, wish fulfilled", reversed: "Dissatisfaction, envy, unfulfilled wishes, emptiness", reading: "The Nine of Cups is the wish card of the tarot. It shows a figure sitting contentedly with nine cups arranged behind them. Your wishes are being fulfilled. This is a time of emotional satisfaction, material comfort, and deep contentment. You have worked hard, and the universe is rewarding you. Allow yourself to feel proud of what you have accomplished and grateful for the abundance in your life.", keywords: ["contentment", "abundance", "gratitude"], advice: "You have everything you need. Gratitude turns what you have into enough." },
    Ten: { name: "Ten of Cups", number: "Ten", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Divine love, fulfillment, harmony, lasting happiness", reversed: "Broken home, disharmony, family conflict, separation", reading: "The Ten of Cups is the card of ultimate emotional fulfillment. It shows a happy family under a rainbow of cups, representing divine love and lasting happiness. This card represents the realization of your deepest emotional desires. A harmonious relationship, a loving family, a sense of belonging and emotional security. You are surrounded by love, and you are at peace.", keywords: ["fulfillment", "harmony", "divine love"], advice: "Love is the foundation of all lasting happiness. Nurture it above all else." },
    Page: { name: "Page of Cups", number: "Page", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Creative opportunity, intuitive messages, curiosity", reversed: "Creative blocks, missed opportunities, immaturity", reading: "The Page of Cups represents creative inspiration and intuitive messages. A young figure offers a cup containing a fish, symbolizing the gifts of the unconscious rising into awareness. A creative opportunity or emotional message is coming your way. Stay open to inspiration from unexpected sources. Your intuition is heightened, and your creative potential is ready to be expressed.", keywords: ["creativity", "intuition", "opportunity"], advice: "A message is coming. Stay open, especially to what arrives through feeling, not logic." },
    Knight: { name: "Knight of Cups", number: "Knight", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Romance, charm, proposal, imagination, beauty", reversed: "Jealousy, moodiness, unrealistic expectations, fantasy", reading: "The Knight of Cups rides forward, holding a cup aloft like an offering. He is the romantic, the dreamer, the one who follows his heart above all else. This card represents a romantic proposal, a creative inspiration, or following your heart's desire. The Knight of Cups invites you to pursue what you love with passion and devotion, but keep one foot on the ground.", keywords: ["romance", "charm", "proposal"], advice: "Let yourself be swept away, but keep one foot on the ground." },
    Queen: { name: "Queen of Cups", number: "Queen", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Emotional security, compassion, nurturing, intuition", reversed: "Codependency, insecurity, emotional volatility, smothering", reading: "The Queen of Cups embodies emotional depth, compassion, and intuitive wisdom. She sits on her throne by the sea, holding a beautiful covered cup, her feet resting on shells. She is deeply connected to the emotional realm and navigates life with empathy and understanding. Her intuition is her greatest guide. This card asks you to lead with your heart, to nurture others from a place of inner security, and to trust your emotional knowing.", keywords: ["compassion", "nurturing", "intuition"], advice: "Your emotional depth is your superpower. Nurture others, but not at your own expense." },
    King: { name: "King of Cups", number: "King", suit: "Cups", arcana: "minor", symbol: SUITS.Cups.symbol, element: SUITS.Cups.element, upright: "Emotional balance, compassion, wisdom, diplomacy", reversed: "Emotional manipulation, moodiness, volatility, coldness", reading: "The King of Cups represents emotional maturity and wisdom. He sits on a throne amid stormy seas, but he remains calm and composed. He has mastered his emotions rather than being ruled by them. This card represents a person who leads with compassion and wisdom, who is able to navigate difficult emotional situations with grace and diplomacy. You are being called to embody this balance — to feel deeply without being overwhelmed by your feelings.", keywords: ["compassion", "wisdom", "diplomacy"], advice: "Rule your emotional kingdom with wisdom. Feel deeply, but act with clarity." },
  },
  Swords: {
    Ace: { name: "Ace of Swords", number: "Ace", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Clarity, mental breakthrough, truth, new idea", reversed: "Confusion, misunderstanding, noise, clouded judgment", reading: "The Ace of Swords cuts through confusion with the power of clarity. A hand emerges from the clouds holding a sword crowned with a wreath and a olive branch. This card represents a breakthrough in understanding — a moment when the truth becomes clear and you see things as they really are. Your mind is sharp, your judgment is clear, and you are able to cut through deception to reach the heart of the matter. Speak your truth with conviction.", keywords: ["clarity", "truth", "breakthrough"], advice: "The truth cuts through illusion. Speak it, even if your voice shakes." },
    Two: { name: "Two of Swords", number: "Two", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Difficult decisions, stalemate, choices, weighing options", reversed: "Lack of clarity, indecision, information overload", reading: "The Two of Swords shows a blindfolded figure holding two crossed swords. This card represents being at a crossroads, unable to see clearly which direction to take. You are weighing two options, but you cannot see all the factors involved. The blindfold suggests that you may be refusing to see the truth, or that the information you need is not yet available. This is a time for patience and careful consideration. Do not rush the decision.", keywords: ["decisions", "stalemate", "choices"], advice: "You cannot see all sides at once. Choose a direction and trust your sight to adjust." },
    Three: { name: "Three of Swords", number: "Three", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Heartbreak, grief, sorrow, betrayal, pain", reversed: "Healing, recovery, forgiveness, releasing pain", reading: "The Three of Swords pierces a heart with three swords. This card represents heartbreak, grief, and emotional pain. A betrayal, a loss, or a painful truth has wounded you deeply. The pain is real, and it demands to be felt. Do not suppress or deny your sorrow. The only way through grief is through it. Allow yourself to feel the pain fully, knowing that healing will follow in its own time.", keywords: ["heartbreak", "grief", "betrayal"], advice: "The wound is real. Allow yourself to grieve before you try to heal." },
    Four: { name: "Four of Swords", number: "Four", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Rest, restoration, meditation, contemplation, retreat", reversed: "Restlessness, burnout, exhaustion, lack of renewal", reading: "The Four of Swords shows a figure lying in rest, with three swords hung above and one beneath. This card represents the need for rest, meditation, and recovery. You have been through a difficult period, and your mind needs time to heal. This is not weakness — it is wisdom. Taking time to rest and restore your mental energy is essential before you can move forward. Give yourself permission to be still.", keywords: ["rest", "restoration", "contemplation"], advice: "Your mind needs stillness. Rest is not laziness; it is preparation." },
    Five: { name: "Five of Swords", number: "Five", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Conflict, defeat, loss, bitterness, humiliation", reversed: "Reconciliation, moving on, forgiveness, past conflicts", reading: "The Five of Swords shows a figure holding three swords, with two defeated figures walking away in the background. This card represents conflict, defeat, and the bitter taste of victory that was not worth the cost. You may have won the battle, but at what expense? Sometimes it is better to walk away than to fight for a hollow victory. In its shadow aspect, this card warns against a win-at-all-costs mentality.", keywords: ["conflict", "defeat", "loss"], advice: "Not every battle is yours to win. Sometimes letting go is the true victory." },
    Six: { name: "Six of Swords", number: "Six", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Transition, moving forward, leaving behind, travel", reversed: "Resistance to change, baggage, unfinished business", reading: "The Six of Swords shows a ferryman carrying a figure and their child across a river, six swords standing in the boat. This card represents transition and moving forward after a difficult period. You are leaving troubled waters behind and heading toward calmer shores. The journey may be uncomfortable, and you must bring with you only what is necessary. Let go of the weight that would sink the boat.", keywords: ["transition", "moving forward", "travel"], advice: "You are crossing into calmer waters. Leave what does not serve you on the shore." },
    Seven: { name: "Seven of Swords", number: "Seven", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Strategy, deception, cunning, stealth, planning", reversed: "Honesty, openness, acknowledging deception, coming clean", reading: "The Seven of Swords shows a figure sneaking away with five swords, leaving two behind. This card represents strategy, deception, and doing what needs to be done with stealth and cunning. In its upright position, it may indicate that you need to be strategic and careful in your approach — not everyone needs to know your plan. In its shadow aspect, it warns against dishonesty and manipulation. Be strategic, but keep your integrity.", keywords: ["strategy", "deception", "cunning"], advice: "Not everyone plays fair. Use your mind wisely, but keep your integrity intact." },
    Eight: { name: "Eight of Swords", number: "Eight", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Restriction, bondage, helplessness, negative thoughts", reversed: "Liberation, empowerment, new perspective, release", reading: "The Eight of Swords shows a blindfolded figure surrounded by eight swords, bound and trapped. Yet the swords do not actually touch her, and the blindfold is loose. This card represents the feeling of being trapped — but the prison is largely in your mind. Your negative thoughts and limiting beliefs are the true bars of this cage. The situation is not as hopeless as it seems. Remove the blindfold and you will see the way out.", keywords: ["restriction", "bondage", "powerlessness"], advice: "The prison is in your mind. The key is in your perception." },
    Nine: { name: "Nine of Swords", number: "Nine", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Anxiety, worry, fear, nightmares, overwhelm", reversed: "Facing fears, hope, overcoming anxiety, peace returning", reading: "The Nine of Swords shows a figure sitting up in bed, head in hands, with nine swords hanging on the wall. This card represents anxiety, worry, and the sleepless nights that come with overwhelming fear. Your mind is creating scenarios that may never come to pass. The darkness of the night magnifies every fear. This card asks you to recognize that much of your suffering is self-created through worry. Seek support, talk to someone, and remember that dawn always comes.", keywords: ["anxiety", "worry", "fear"], advice: "Fear is a liar wearing a convincing mask. Look beneath fear and find the truth." },
    Ten: { name: "Ten of Swords", number: "Ten", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Rock bottom, crisis, betrayal, painful ending", reversed: "Recovery, healing, lessons learned, survival", reading: "The Ten of Swords shows a figure lying face down with ten swords in their back. The sky is black, but in the distance, the horizon is lightening. This card represents rock bottom — the most painful ending, the worst betrayal, the deepest crisis. It looks grim. But here is the hopeful truth: when you are at the very bottom, there is nowhere to go but up. The dawn is approaching. This ending, however painful, is final. You can now begin to heal.", keywords: ["rock bottom", "crisis", "ending"], advice: "When you hit bottom, the only direction is up. This too shall pass." },
    Page: { name: "Page of Swords", number: "Page", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "New ideas, curiosity, communication, intellectual pursuit", reversed: "Gossip, hasty words, miscommunication, cynicism", reading: "The Page of Swords represents intellectual curiosity and the pursuit of truth. A young figure holds a sword aloft, ready to learn and explore. This card signals new ideas, stimulating conversations, and the desire to understand the world more deeply. Your mind is sharp and your curiosity is high. Use this energy to learn something new, to ask important questions, and to communicate your ideas with clarity and precision.", keywords: ["ideas", "curiosity", "communication"], advice: "Your voice carries power. Speak your truth, but choose your words with care." },
    Knight: { name: "Knight of Swords", number: "Knight", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Ambition, action, determination, charge forward", reversed: "Recklessness, aggression, burnout, impulsiveness", reading: "The Knight of Swords charges into battle with relentless determination. This card represents the need for swift action and decisive movement. Your mind is made up, and you are ready to charge forward. The Knight does not hesitate — he acts. This energy is powerful, but it also carries the risk of recklessness. Be determined in your pursuit, but make sure you have considered the consequences of your actions.", keywords: ["ambition", "action", "determination"], advice: "Charge forward with purpose, but remember that not every battle needs a soldier." },
    Queen: { name: "Queen of Swords", number: "Queen", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Perception, clarity, independent thought, truth", reversed: "Coldness, bitterness, loneliness, harsh judgment", reading: "The Queen of Swords represents clear perception and the power of independent thought. She sits on her throne, holding a sword upright, her gaze direct and unwavering. She sees through deception and values truth above comfort. Her communication is direct, honest, and sometimes sharp. This card asks you to think for yourself, to speak your truth clearly, and to make decisions based on facts and reason rather than emotion. Clarity is your greatest ally right now.", keywords: ["clarity", "perception", "truth"], advice: "Seek the truth with compassion. Clarity without kindness is just cruelty." },
    King: { name: "King of Swords", number: "King", suit: "Swords", arcana: "minor", symbol: SUITS.Swords.symbol, element: SUITS.Swords.element, upright: "Authority, truth, justice, intellect, moral clarity", reversed: "Misuse of power, manipulation, coldness, tyranny", reading: "The King of Swords represents intellectual authority and moral clarity. He sits on his throne holding a sword, representing the power of truth and justice. He has mastered the realm of air — his thoughts are disciplined, his judgment is fair, and his communication is clear. This card asks you to lead with your intellect and your conscience. Make decisions based on truth and fairness, not emotion or self-interest.", keywords: ["authority", "truth", "intellect"], advice: "Lead with your mind and your conscience. True authority serves justice." },
  },
  Pentacles: {
    Ace: { name: "Ace of Pentacles", number: "Ace", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "New opportunity, prosperity, abundance, growth", reversed: "Missed opportunity, lack of planning, scarcity mindset", reading: "The Ace of Pentacles represents a new opportunity for material prosperity and abundance. A hand emerges from the clouds, offering a golden pentacle. This card often signals a financial opportunity, a new job, a business venture, or any chance to build something of lasting material value. The seed of prosperity is being offered to you. Your job is to plant it with care, nurture it with patience, and not let fear prevent you from grasping the opportunity before you.", keywords: ["opportunity", "prosperity", "abundance"], advice: "A seed of prosperity is offered. Plant it with care and patience." },
    Two: { name: "Two of Pentacles", number: "Two", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Balance, adaptation, resource management, juggling", reversed: "Overextension, imbalance, disorganization, chaos", reading: "The Two of Pentacles shows a figure juggling two pentacles while standing on uneven ground. This card represents the challenge of balancing multiple priorities and responsibilities. You are managing competing demands on your time, energy, and resources. The key is adaptation and flexibility — the figure in the card is moving with the rhythm of the waves rather than fighting them. Keep your balance by staying adaptable.", keywords: ["balance", "adaptation", "resources"], advice: "Life is a balancing act. Prioritize what matters most and release the rest." },
    Three: { name: "Three of Pentacles", number: "Three", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Teamwork, collaboration, skill building, mastery", reversed: "Lack of teamwork, poor quality, mediocre standards", reading: "The Three of Pentacles depicts a craftsman working alongside an architect and a monk, collaborating on a cathedral. This card represents teamwork, collaboration, and the mastery of a craft through dedicated practice. You are being called to work with others, to learn from those with more experience, and to bring your best skills to a collective project. Great things are built through cooperation and mutual respect.", keywords: ["teamwork", "collaboration", "mastery"], advice: "No masterpiece was ever built alone. Collaborate and learn from others." },
    Four: { name: "Four of Pentacles", number: "Four", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Security, conservation, stability, saving, guarding", reversed: "Greed, materialism, possessiveness, hoarding", reading: "The Four of Pentacles shows a figure clutching two pentacles, with two more under his feet. This card represents the desire for financial security and stability. You are holding tightly to what you have, perhaps out of fear of losing it. While prudence is wise, this card warns against letting fear of scarcity prevent you from living fully. There is a difference between wise stewardship and anxious hoarding.", keywords: ["security", "stability", "saving"], advice: "Security is good; hoarding is fear. Save wisely, but do not let fear lock your abundance." },
    Five: { name: "Five of Pentacles", number: "Five", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Financial loss, poverty, isolation, insecurity", reversed: "Recovery, spiritual wealth, finding help, hope", reading: "The Five of Pentacles shows two figures outside in the snow, walking past a lighted church window. This card represents material hardship, financial loss, and the feeling of being left out in the cold. Yet the church window represents spiritual comfort and community support that is available if you are willing to seek it. You may be experiencing lack, but you are not truly alone. Help is available. Do not let pride or shame prevent you from reaching out.", keywords: ["loss", "poverty", "insecurity"], advice: "When material wealth fails, you discover what you are truly made of." },
    Six: { name: "Six of Pentacles", number: "Six", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Charity, generosity, giving, receiving, sharing", reversed: "Strings attached charity, inequality, debt, dependence", reading: "The Six of Pentacles shows a figure weighing coins and distributing them to two beggars. This card represents generosity, charity, and the balance of giving and receiving. You may be in a position to give — whether that is money, time, or wisdom — or you may be in need of receiving. Both are sacred. Give without expecting return, and receive with gratitude. The flow of generosity maintains the health of the community.", keywords: ["generosity", "charity", "sharing"], advice: "Give freely without strings. True generosity expects nothing in return." },
    Seven: { name: "Seven of Pentacles", number: "Seven", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Patience, investment, planning, long-term vision", reversed: "Impatience, poor planning, short-term thinking", reading: "The Seven of Pentacles shows a farmer leaning on his hoe, surveying the crop he has planted. This card represents the patience required for long-term investment. You have done the hard work of planting, and now you must wait for the harvest. It is natural to feel impatient, to wonder if your efforts will bear fruit. The farmer must trust the process, continue to tend the field, and wait for the natural cycle to complete itself. Your patience will be rewarded.", keywords: ["patience", "investment", "planning"], advice: "What you plant today will not bear fruit tomorrow. Be patient with the process." },
    Eight: { name: "Eight of Pentacles", number: "Eight", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Apprenticeship, skill development, dedication, excellence", reversed: "Perfectionism, lack of skill, poor quality, shortcuts", reading: "The Eight of Pentacles depicts a craftsman hard at work, creating pentacles with focused dedication. This card represents the commitment to mastering a skill through dedicated practice and attention to detail. You are in a period of learning and growth. The work may be repetitive or unglamorous, but each small effort is building toward mastery. Stay focused, stay humble, and trust the process of gradual improvement.", keywords: ["skill", "dedication", "craftsmanship"], advice: "Mastery is the accumulation of small, consistent efforts. Keep working." },
    Nine: { name: "Nine of Pentacles", number: "Nine", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Luxury, self-sufficiency, financial independence, comfort", reversed: "Overspending, dependence, financial insecurity, loneliness", reading: "The Nine of Pentacles shows a woman in a lush garden, wearing fine clothes, with a pentacle nearby. A bird perches on her gloved hand. This card represents financial independence, self-sufficiency, and the enjoyment of the good life. You have built a life of comfort and security through your own efforts. Enjoy the luxuries you have earned, but do not become complacent or isolated in your success. True abundance is meant to be shared.", keywords: ["luxury", "self-sufficiency", "abundance"], advice: "You have built something to be proud of. Enjoy it, but do not forget those who helped." },
    Ten: { name: "Ten of Pentacles", number: "Ten", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Wealth, legacy, inheritance, family prosperity", reversed: "Financial loss, family disputes, bankruptcy, instability", reading: "The Ten of Pentacles represents the culmination of material success and the establishment of a lasting legacy. It shows a prosperous family scene, with an elderly patriarch, a married couple, children, and dogs — representing generational wealth and family continuity. This card speaks to inheritance, family traditions, and the long-term stability that comes from wise stewardship. What you build now can benefit generations to come.", keywords: ["wealth", "legacy", "prosperity"], advice: "True wealth is not what you leave for people, but what you leave in people." },
    Page: { name: "Page of Pentacles", number: "Page", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Ambition, diligence, learning, new skills, practicality", reversed: "Lack of progress, laziness, missed deadlines, immaturity", reading: "The Page of Pentacles represents the beginning of a journey toward material mastery. A young figure holds a pentacle, gazing at it with focused attention. This card signals a new opportunity for learning a practical skill, starting a financial endeavor, or committing to a path of disciplined growth. Your attitude is one of diligence and ambition. Stay grounded, stay focused, and be willing to start at the beginning.", keywords: ["ambition", "diligence", "learning"], advice: "Every master was once a beginner. Stay curious and committed to learning." },
    Knight: { name: "Knight of Pentacles", number: "Knight", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Hard work, responsibility, diligence, reliability", reversed: "Laziness, irresponsibility, burnout, workaholism", reading: "The Knight of Pentacles moves forward steadily, holding a pentacle with unwavering focus. He is the slowest of the knights, but also the most reliable. This card represents hard work, responsibility, and the steady, determined pursuit of goals. There are no shortcuts here — only consistent effort and attention to detail. Your reliability is your strength, and your patience will yield results. Keep going.", keywords: ["hard work", "responsibility", "reliability"], advice: "Slow and steady wins the race. Your reliability is your greatest asset." },
    Queen: { name: "Queen of Pentacles", number: "Queen", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Nurturing, practicality, abundance, security, grounding", reversed: "Neglect, financial insecurity, smothering, dependence", reading: "The Queen of Pentacles embodies nurturing abundance and practical wisdom. She sits on a throne decorated with animals and vines, holding a pentacle, surrounded by lush nature. She is the caretaker, the provider, the one who creates a home of warmth and stability. This card asks you to tend to the practical needs of yourself and those you love. Create security through wise management of resources, and let your generosity flow from a foundation of stability.", keywords: ["nurturing", "practicality", "abundance"], advice: "Create a sanctuary of stability and warmth. Generosity flows from security." },
    King: { name: "King of Pentacles", number: "King", suit: "Pentacles", arcana: "minor", symbol: SUITS.Pentacles.symbol, element: SUITS.Pentacles.element, upright: "Abundance, leadership, success, financial mastery", reversed: "Greed, materialism, stubbornness, financial mismanagement", reading: "The King of Pentacles represents the pinnacle of material success and financial mastery. He sits on his throne, surrounded by the abundance he has generated, holding his scepter and pentacle. He has achieved mastery over the material world through discipline, wisdom, and hard work. This card represents the culmination of your efforts in the material realm. You have earned your success through competence and integrity. Use your abundance wisely and generously.", keywords: ["abundance", "success", "leadership"], advice: "Use your success to create more than money. Leave a legacy of wisdom." },
  },
};

function buildDeck(): TarotCard[] {
  const deck: TarotCard[] = MAJOR_ARCANA.map((c) => ({ ...c }));
  for (const suit of ["Wands", "Cups", "Swords", "Pentacles"] as const) {
    for (const num of MINOR_NUMBERS) {
      const card = MINOR_READINGS[suit]?.[num];
      if (card) deck.push({ ...card });
    }
  }
  return deck;
}

const DECK = buildDeck();

type Spread = "single" | "three" | "celtic";

const SPREADS: Record<Spread, { label: string; positions: string[] }> = {
  single: { label: "Single Card", positions: ["Your Energy"] },
  three: { label: "Three Card", positions: ["Past — What Shaped You", "Present — Your Current Path", "Future — What Approaches"] },
  celtic: { label: "Celtic Cross", positions: ["Present Situation", "Challenge", "Foundation (Past)", "Immediate Future", "Above (Conscious Goal)", "Below (Subconscious)", "Self (Advice)", "Environment", "Hopes & Fears", "Outcome"] },
};

const SUIT_EMOJI: Record<string, string> = { Wands: "🔥", Cups: "💧", Swords: "💨", Pentacles: "🌍" };

function getSuitColor(suit: string): string {
  return SUIT_COLORS[suit] ?? "#6b4fa0";
}

const MAJOR_TO_FILE: Record<string, string> = {
  "The Fool": "fool", "The Magician": "magician", "The High Priestess": "priestess",
  "The Empress": "empress", "The Emperor": "emperor", "The Hierophant": "hierophant",
  "The Lovers": "lovers", "The Chariot": "chariot", "Strength": "strength",
  "The Hermit": "hermit", "Wheel of Fortune": "fortune", "Justice": "justice",
  "The Hanged Man": "hanged", "Death": "death", "Temperance": "temperance",
  "The Devil": "devil", "The Tower": "tower", "The Star": "star",
  "The Moon": "moon", "The Sun": "sun", "Judgement": "judgement", "The World": "world",
};

const MINOR_RANK_TO_FILE: Record<string, string> = {
  "Ace": "ace", "Two": "2", "Three": "3", "Four": "4", "Five": "5",
  "Six": "6", "Seven": "7", "Eight": "8", "Nine": "9", "Ten": "10",
  "Page": "page", "Knight": "knight", "Queen": "queen", "King": "king",
};

function getCardImage(card: TarotCard): string {
  if (card.arcana === "major") {
    const key = MAJOR_TO_FILE[card.name];
    return key ? `/tarot/major_arcana_${key}.png` : "";
  }
  const suit = card.suit.toLowerCase();
  const rank = MINOR_RANK_TO_FILE[card.number ?? ""] ?? "";
  return rank ? `/tarot/minor_arcana_${suit}_${rank}.png` : "";
}

function getConclusion(cards: { card: TarotCard; reversed: boolean }[], spread: Spread): string {
  const isReversed = (i: number) => cards[i]?.reversed ?? false;
  const name = (i: number) => cards[i]?.card.name ?? "";

  if (spread === "single") {
    const c = cards[0];
    if (!c) return "";
    const base = c.reversed ? c.card.reversed : c.card.upright;
    return `This single card reading centers on ${c.card.name}. ${base}. ${c.card.advice} The energy of this card is your focus for now. Sit with its message and notice how it reflects in your daily life over the coming days.`;
  }

  if (spread === "three") {
    const parts: string[] = [];
    if (cards[0]) parts.push(`Your past has been shaped by ${name(0)}${isReversed(0) ? " in reverse" : ""}.`);
    if (cards[1]) parts.push(`Your present path is guided by ${name(1)}${isReversed(1) ? " in reverse" : ""}.`);
    if (cards[2]) parts.push(`The future brings the energy of ${name(2)}${isReversed(2) ? " in reverse" : ""}.`);
    return `Together, these three cards tell a story of movement. ${parts.join(" ")} The thread connecting them is the lesson you are here to learn: how your past informs your present, and how your present choices shape your future. The cards suggest that awareness of this pattern is itself the beginning of change.`;
  }

  if (spread === "celtic") {
    const crossCards = cards.slice(0, 6);
    const outcome = cards[9];
    const majors = cards.filter((c) => c.card.arcana === "major");
    const keyMessage = majors.length > 0
      ? `The presence of ${majors.length} Major Arcana card${majors.length > 1 ? "s" : ""} (${majors.map((c) => c.card.name).join(", ")}) indicates this is a significant life period with deep karmic themes.`
      : "The focus is on practical, day-to-day matters guided by the Minor Arcana.";
    return `This Celtic Cross spread reveals a complex picture. ${keyMessage} The central cross (positions 1-6) shows the core dynamic of your situation, while the staff (positions 7-10) reveals the broader context and likely outcome. ${outcome ? `The outcome card, ${outcome.card.name}${outcome.reversed ? " in reverse" : ""}, suggests where this path is leading.` : ""} The overall message is one of integration — bringing together the conscious and unconscious, the internal and external, to move forward with clarity and purpose.`;
  }

  return "";
}

export default function TarotPage() {
  const [spread, setSpread] = useState<Spread>("single");
  const [cards, setCards] = useState<{ card: TarotCard; reversed: boolean }[]>([]);
  const [dealt, setDealt] = useState(false);

  const deal = () => {
    const count = SPREADS[spread].positions.length;
    const shuffled = [...DECK].sort(() => Math.random() - 0.5).slice(0, count);
    setCards(shuffled.map((c) => ({ card: c, reversed: Math.random() < 0.3 })));
    setDealt(true);
  };

  const conclusion = useMemo(() => getConclusion(cards, spread), [cards, spread]);

  return (
    <div className="flex flex-col items-center min-h-screen px-4 py-12">
      <div className="absolute top-4 right-4">
        <ThemeToggle />
      </div>
      <h1 className="apple-headline text-[34px] leading-[1.47] tracking-[-0.374px] mb-2">
        Tarot Reading
      </h1>
      <p className="text-[13px] text-[var(--color-ink-muted-48)] mb-8 text-center max-w-lg">
        A full 78-card deck with detailed readings for every card.
      </p>

      <div className="w-full max-w-2xl apple-card px-6 py-5 mb-5">
        <div className="flex gap-2">
          {(Object.entries(SPREADS) as [Spread, typeof SPREADS[Spread]][]).map(([key, s]) => (
            <button
              key={key}
              onClick={() => { setSpread(key); setCards([]); setDealt(false); }}
              className={`flex-1 px-3 py-2.5 rounded-[11px] text-[13px] font-semibold transition-all ${
                spread === key
                  ? "bg-[var(--color-primary)] text-white"
                  : "bg-[var(--color-surface-pearl)] text-[var(--color-ink-muted-48)] hover:brightness-95"
              }`}
            >
              {s.label}
            </button>
          ))}
        </div>
      </div>

      <button
        onClick={deal}
        className="apple-btn-primary h-12 px-10 text-[15px] font-semibold mb-6"
      >
        Shuffle & Deal
      </button>

      {dealt && cards.length > 0 && (
        <div className="w-full max-w-4xl space-y-5">
          <div className={`grid gap-4 ${
            spread === "celtic" ? "grid-cols-1 sm:grid-cols-2" : spread === "three" ? "grid-cols-1 sm:grid-cols-3" : "grid-cols-1 sm:grid-cols-1 max-w-sm mx-auto"
          }`}>
            {cards.map(({ card, reversed }, i) => {
              const suitColor = getSuitColor(card.suit);
              return (
                <div key={i} className="flex flex-col items-center">
                  <div
                    className="w-full max-w-[200px] rounded-[14px] p-4 flex flex-col items-center"
                    style={{
                      background: "linear-gradient(145deg, #faf5eb, #f0e8d8)",
                      border: `2px solid ${suitColor}40`,
                      boxShadow: `0 4px 20px ${suitColor}20`,
                    }}
                  >
                    <div className="text-[13px] font-bold text-center" style={{ color: suitColor }}>
                      {card.arcana === "major" ? MAJOR_SYMBOLS[card.name] ?? "" : card.number}
                    </div>
                    <img
                      src={getCardImage(card)}
                      alt={card.name}
                      className="w-[110px] h-auto my-1.5 rounded-[6px] shadow-sm"
                      loading="lazy"
                    />
                    <div className="text-[14px] font-bold text-center text-[#1a1a1a] leading-tight">{card.name}</div>
                    <div className="text-[9px] text-center mt-1 px-2 py-0.5 rounded-full" style={{ background: `${suitColor}20`, color: suitColor }}>
                      {card.suit === "Major Arcana" ? "Major Arcana" : `${card.suit} (${card.element})`}
                    </div>
                    {reversed && (
                      <div className="text-[9px] text-red-500 font-semibold mt-1 uppercase tracking-wider">Reversed</div>
                    )}
                  </div>
                  <div className="text-[10px] text-[var(--color-ink-muted-48)] mt-2 font-semibold text-center">
                    {SPREADS[spread].positions[i]}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Detailed readings for each card */}
          {cards.map(({ card, reversed }, i) => (
            <div key={`reading-${i}`} className="apple-card px-6 py-5">
              <div className="flex items-start justify-between mb-1">
                <div>
                  <h3 className="text-[17px] font-bold text-[var(--color-ink)]">{card.name}</h3>
                  <div className="text-[11px] text-[var(--color-ink-muted-48)]">
                    {SPREADS[spread].positions[i]}
                    {reversed && <span className="text-red-500 ml-2 font-semibold">Reversed</span>}
                  </div>
                </div>
                <div className="text-[11px] text-right shrink-0" style={{ color: getSuitColor(card.suit) }}>
                  <div>{card.suit === "Major Arcana" ? "Major Arcana" : card.suit}</div>
                  <div className="text-[var(--color-ink-muted-48)]">{card.element}</div>
                </div>
              </div>

              <p className="text-[13px] leading-[1.7] text-[var(--color-ink)] mt-2">
                {card.reading}
              </p>

              <div className="flex flex-wrap gap-1.5 mt-3">
                {card.keywords.map((kw) => (
                  <span key={kw} className="px-2 py-0.5 rounded-[6px] text-[10px] bg-[var(--color-surface-pearl)] text-[var(--color-ink-muted-48)]">{kw}</span>
                ))}
              </div>

              <div className="mt-3 px-4 py-3 rounded-[11px]" style={{ background: `${getSuitColor(card.suit)}0D` }}>
                <div className="text-[10px] font-semibold uppercase tracking-wider mb-1" style={{ color: getSuitColor(card.suit) }}>
                  {reversed ? "Reversed Meaning" : "Upright Meaning"}
                </div>
                <p className="text-[13px] leading-[1.6] text-[var(--color-ink)]">{reversed ? card.reversed : card.upright}</p>
              </div>

              <div className="mt-3 px-4 py-3 rounded-[11px] bg-[var(--color-surface-pearl)]">
                <div className="text-[10px] font-semibold uppercase tracking-wider text-[var(--color-ink-muted-48)] mb-1">Advice</div>
                <p className="text-[13px] leading-[1.6] italic text-[var(--color-ink)]">&ldquo;{card.advice}&rdquo;</p>
              </div>
            </div>
          ))}

          {/* Conclusion */}
          <div className="apple-card px-6 py-5 border-l-4" style={{ borderLeftColor: "var(--color-primary)" }}>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-[18px]">📜</span>
              <h3 className="text-[14px] font-bold uppercase tracking-wider text-[var(--color-ink)]">Reading Conclusion</h3>
            </div>
            <p className="text-[13px] leading-[1.8] text-[var(--color-ink)]">{conclusion}</p>
          </div>
        </div>
      )}

      {!dealt && (
        <div className="w-full max-w-2xl apple-card px-6 py-5">
          <h2 className="text-[12px] font-semibold uppercase text-[var(--color-ink-muted-48)] mb-2">About Tarot</h2>
          <p className="text-[13px] leading-[1.6] text-[var(--color-ink)] mb-2">
            The tarot deck contains 78 cards: 22 Major Arcana representing life's major archetypal lessons, and 56 Minor Arcana divided into four suits — Wands (fire, creativity), Cups (water, emotions), Swords (air, intellect), and Pentacles (earth, material).
          </p>
          <p className="text-[13px] leading-[1.6] text-[var(--color-ink)]">
            Choose a spread above and press Shuffle &amp; Deal. Each card includes a full interpretive reading, keywords, upright/reversed meanings, and guidance. A synthesized conclusion follows the spread.
          </p>
        </div>
      )}

      <p className="text-[10px] text-[var(--color-ink-muted-48)] mt-8 text-center max-w-lg">
        Cards sourced from the public domain <strong>Rider-Waite-Smith tarot</strong> (1909) by A.E. Waite and Pamela Colman Smith, via the <a href="https://archive.org/details/rider-waite-tarot" target="_blank" rel="noopener noreferrer" className="underline">Internet Archive</a>.
      </p>
    </div>
  );
}
